### ISSUE TITLE
Add a Pull Request template

### ISSUE THREAD

**Issue by alexmarginean16** [alexmarginean16/codesession#3]
- add a pull request template to resolve issues (create PULL_REQUEST_TEMPLATE.md and add from below)
        
        Fixes #issuenumber

        Check everything which applies
        
        - [ ] Add changes

- Try to promote the project more so other people can contribute

**Comment by KiSobral** [comment]
Hey, I could do this for you :)

Is anyone working on it right now?

**Comment by chippyho123** [comment]
I am

**Comment by alexmarginean16** [comment]
> Hey, I could do this for you :)
> 
> Is anyone working on it right now?

Hi, I wasn't sure if anyone was working on it but now I saw that @chippyho123 already made a pull request.

**Comment by alexmarginean16** [comment]
This issue was solved
